swagger: '2.0'
info:
  description: This is Song projector Middleware service.
  version: 1.0.0
  title: Song projector Middleware service
  contact:
    email: songprojector@gmail.com
  license:
    name: MIT License
    url: http://opensource.org/licenses/MIT
host: localhost:8080
basePath: /
tags:
  - name: users
    description: Operations about users
paths:
  /users/me:
    get:
      tags:
        - users
      summary: Returns current user's data
      operationId: whoamiUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/UserResponseDTO'
        '400':
          description: Something went wrong
        '403':
          description: Access denied
        '500':
          description: Expired or invalid JWT token
      security:
        - Authorization:
            - global
        - apiKey: []
      deprecated: false
  /users/refresh:
    get:
      tags:
        - users
      summary: Refreshes the Access token
      operationId: refreshUsingGET
      produces:
        - '*/*'
      parameters:
        - in: body
          name: refreshToken
          description: Refresh Token
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Invalid refresh token
      security:
        - Authorization:
            - global
      deprecated: false
  /users/signin:
    post:
      tags:
        - users
      summary: Authenticates user and returns Access token and Refresh token
      operationId: loginUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: loginData
          description: Signup User
          required: false
          schema:
            $ref: '#/definitions/LoginDataDTO'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/TokenDTO'
        '400':
          description: Something went wrong
        '401':
          description: Invalid username/password supplied
      security:
        - Authorization:
            - global
      deprecated: false
  /users/signup:
    post:
      tags:
        - users
      summary: Creates user and returns Access token and Refresh token
      operationId: signupUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: user
          description: Signup User
          required: false
          schema:
            $ref: '#/definitions/UserDataDTO'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/TokenDTO'
        '400':
          description: Something went wrong
        '409':
          description: Username is already in use
      security:
        - Authorization:
            - global
      deprecated: false
  /users/you:
    get:
      tags:
        - users
      summary: you
      operationId: youUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/UserResponseDTO'
      security:
        - Authorization:
            - global
      deprecated: false
  /users/{username}:
    get:
      tags:
        - users
      summary: Returns specific user by username
      operationId: searchUsingGET
      produces:
        - '*/*'
      parameters:
        - name: username
          in: path
          description: Username
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/UserResponseDTO'
        '400':
          description: Something went wrong
        '403':
          description: Access denied
        '404':
          description: The user doesn't exist
        '500':
          description: Expired or invalid JWT token
      security:
        - Authorization:
            - global
        - apiKey: []
      deprecated: false
    delete:
      tags:
        - users
      summary: Deletes specific user by username
      operationId: deleteUsingDELETE
      produces:
        - '*/*'
      parameters:
        - name: username
          in: path
          description: Username
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
        '400':
          description: Something went wrong
        '403':
          description: Access denied
        '404':
          description: The user doesn't exist
        '500':
          description: Expired or invalid JWT token
      security:
        - Authorization:
            - global
        - apiKey: []
      deprecated: false
securityDefinitions:
  Authorization:
    type: apiKey
    name: Authorization
    in: header
definitions:
  LoginDataDTO:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
    title: LoginDataDTO
  TokenDTO:
    type: object
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    title: TokenDTO
  UserDataDTO:
    type: object
    properties:
      email:
        type: string
      organizationName:
        type: string
      password:
        type: string
      username:
        type: string
    title: UserDataDTO
  UserResponseDTO:
    type: object
    properties:
      id:
        type: string
      username:
        type: string
      email:
        type: string
      appUserRoles:
        type: array
        items:
          type: string
          enum:
            - ADMIN_ORG
            - MEMBER_ORG
            - NO_ORG
    title: UserResponseDTO
